# Generated by Django 3.0.2 on 2020-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='edad',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
