# Generated by Django 3.0.2 on 2020-01-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0002_conductores_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carros',
        ),
        migrations.AlterUniqueTogether(
            name='conductores',
            unique_together={('nombres', 'apellidos')},
        ),
    ]
