# Generated by Django 3.0.2 on 2020-01-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0004_carros'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conductores',
            unique_together=set(),
        ),
    ]
