# Generated by Django 3.0.2 on 2020-01-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0005_auto_20200109_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conductores',
            unique_together={('nombres', 'apellidos')},
        ),
    ]
