# Generated by Django 3.0.2 on 2020-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0008_auto_20200110_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizas',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='polizas/'),
        ),
    ]
