# Generated by Django 3.0.2 on 2020-01-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0010_propietarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='conductores',
            options={'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='polizas',
            options={'verbose_name_plural': 'Polizas'},
        ),
        migrations.AlterModelOptions(
            name='propietarios',
            options={'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AddField(
            model_name='carros',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AC.propietarios'),
            preserve_default=False,
        ),
    ]
