# Generated by Django 3.0.2 on 2020-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0011_auto_20200110_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
