# Generated by Django 3.0.2 on 2020-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0013_conductores_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='ine',
            field=models.FileField(blank=True, null=True, upload_to='INE/'),
        ),
    ]
