# Generated by Django 3.0.2 on 2020-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0015_propietarios_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Gasto',
            },
        ),
    ]
