# Generated by Django 3.0.2 on 2020-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0017_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
