# Generated by Django 3.0.2 on 2020-01-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0019_gasto_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name_plural': 'Gastos'},
        ),
    ]
