# Generated by Django 3.0.2 on 2020-01-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0021_auto_20200113_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('renta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC.carros')),
            ],
            options={
                'verbose_name_plural': 'Rentas',
            },
        ),
    ]
