# Generated by Django 3.0.2 on 2020-01-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0024_pagos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pagos',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AC.carros'),
            preserve_default=False,
        ),
    ]
