# Generated by Django 3.0.2 on 2020-02-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AC', '0050_auto_20200225_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AC.Conductores'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC.Propietarios'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC.Carros'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AC.TipoGasto'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC.Carros'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AC.Renta'),
        ),
        migrations.AlterField(
            model_name='polizas',
            name='carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AC.Carros'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC.Carros'),
        ),
        migrations.CreateModel(
            name='Inactividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AC.Carros')),
            ],
            options={
                'verbose_name_plural': 'Razon de Inactividad',
            },
        ),
    ]
